<?php echo $this->getSst(); ?>
<form id="integratedcheckoufrm" action="<?php echo $this->getSubmitUrl(); ?>" >
    <input type="hidden" name="SST" value="" />
    <input type="hidden" name="SessionId" value="<?php echo $this->getSessionId(); ?>" />
</form>
<script>
    window.onload = function() {
        document.getElementsByName("SST")[1].value = document.getElementsByName("SST")[0].value;
        document.getElementById("integratedcheckoufrm").submit();
    }
</script>
<style>
    body{background:transparent;}
    .page-wrapper{display:none;}    
</style>